language: python

cache:
  directories:
    - pip_download_cache

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE

install:
  - pip install tox
  - pip install -e .

script:
  - python manage.py test

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"

matrix:
  include:
    - python: "3.7"
      env: TOX_ENV=py37-django2.1
      dist: xenial
      sudo: true

notifications:
  email:
    recipients:
      - martinmogusu@gmail.com
    on_success: always
    on_failure: always